// Supabase Edge Function. The logic lives in packages/functions/src/; bundle.mjs is generated by `npm run build:functions`.
import { serve } from "./bundle.mjs";

Deno.serve(serve(Deno.env.toObject()));
