// Publishes the admin page at a secret path: apps/web/admin/index.html -> apps/web/public/<ADMIN_SLUG>/index.html,
// with the admin API URL filled in. Next copies public/ into the static export. ADMIN_SLUG lives in .env and in
// Netlify's environment variables, never in the repo. The slug only hides the page; the Phantom sign-in with
// ADMIN_WALLET (checked by the `admin` Edge Function) protects it.
//   node --env-file-if-exists=.env scripts/build-admin.mjs
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const MARKER = ".admin-generated"; // marks folders this script made, so an old slug gets removed
const RESERVED = new Set(["api", "admin", "launch", "coin", "profile", "how-it-works", "_next"]);

export function buildAdmin({ slug, supabaseUrl, webDir = path.join("apps", "web") }) {
  // Netlify lowercases request paths (and 301s mixed-case ones), so the page lives at the lowercase slug.
  slug = String(slug ?? "").trim().replace(/^\/+|\/+$/g, "").toLowerCase();
  if (!/^[a-z0-9_-]{8,64}$/.test(slug) || RESERVED.has(slug)) {
    throw new Error("ADMIN_SLUG must be 8-64 letters, digits, - or _ (e.g. hq-7f3k2q9x), and not a site page name. Set it in .env and in Netlify.");
  }
  const base = String(supabaseUrl ?? "").trim().replace(/\/+$/, "");
  if (!/^https?:\/\/[^\s"'<>]+$/.test(base)) {
    throw new Error("NEXT_PUBLIC_SUPABASE_URL must be set (https://<project>.supabase.co) so the admin page can reach the admin API.");
  }

  const pub = path.join(webDir, "public");
  fs.mkdirSync(pub, { recursive: true });
  for (const name of fs.readdirSync(pub)) {
    const dir = path.join(pub, name);
    if (name !== slug && fs.existsSync(path.join(dir, MARKER))) fs.rmSync(dir, { recursive: true, force: true });
  }
  const dir = path.join(pub, slug);
  if (fs.existsSync(dir) && !fs.existsSync(path.join(dir, MARKER))) {
    throw new Error(`apps/web/public/${slug} already exists and isn't the admin page. Pick another ADMIN_SLUG.`);
  }
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, MARKER), "");
  fs.writeFileSync(path.join(dir, ".gitignore"), "*\n"); // the slug never gets committed

  const html = fs.readFileSync(path.join(webDir, "admin", "index.html"), "utf8");
  if (!html.includes("%%ADMIN_API%%")) throw new Error("apps/web/admin/index.html lost its %%ADMIN_API%% placeholder.");
  fs.writeFileSync(path.join(dir, "index.html"), html.replace("%%ADMIN_API%%", `${base}/functions/v1/admin`));

  fs.writeFileSync(path.join(pub, "_headers"), [
    "# generated by scripts/build-admin.mjs",
    ...[`/${slug}`, `/${slug}/*`].flatMap((p) => [
      p,
      "  X-Robots-Tag: noindex, nofollow",
      "  X-Frame-Options: DENY",
      "  Cache-Control: no-store",
      "  Referrer-Policy: no-referrer",
    ]),
    "",
  ].join("\n"));
  return slug;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const slug = buildAdmin({ slug: process.env.ADMIN_SLUG, supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL });
    console.log(`Admin page: /${slug}/`);
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
